global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'waf-reverse-proxy'
    static_configs:
      - targets: ['waf-proxy:9090']
    scrape_interval: 5s
    metrics_path: /metrics
    scrape_timeout: 10s
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'waf-admin-api'
    static_configs:
      - targets: ['waf-proxy:8081']
    metrics_path: /api/metrics
    scrape_interval: 30s
